CREATE TABLE IF NOT EXISTS users
(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(250)         NOT NULL,
    email   VARCHAR(254) UNIQUE NOT NULL
);


CREATE TABLE IF NOT EXISTS categories
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name    VARCHAR(50)   UNIQUE      NOT NULL
);


CREATE TABLE IF NOT EXISTS events
(
    event_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation        VARCHAR(2000)                              NOT NULL,
    category_id       BIGINT REFERENCES categories (category_id) NOT NULL,
    confirmed_requests INTEGER,
    created_on         TIMESTAMP WITHOUT TIME ZONE                NOT NULL,
    description       VARCHAR(7000)                              NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE                NOT NULL,
    user_id           BIGINT REFERENCES users (user_id)          NOT NULL,
    lat                FLOAT                                    NOT NULL,
    lon                FLOAT                                    NOT NULL,
    paid              BOOLEAN                                    NOT NULL,
    participant_limit  INTEGER,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state             VARCHAR(50)                                NOT NULL,
    title             VARCHAR(120)                               NOT NULL,
    views             BIGINT ,
    likes             BIGINT ,
    dislikes          BIGINT
);


CREATE TABLE IF NOT EXISTS participation_requests
(
participation_request_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
created                    TIMESTAMP WITHOUT TIME ZONE                NOT NULL,
event                      BIGINT REFERENCES events (event_id)        NOT NULL,
requester                  BIGINT REFERENCES users (user_id)          NOT NULL,
status                     VARCHAR(50)                                NOT NULL
);


CREATE TABLE IF NOT EXISTS compilations
(
compilation_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
pinned            BOOLEAN                                    NOT NULL,
title             VARCHAR(200)       UNIQUE                  NOT NULL
);


CREATE TABLE IF NOT EXISTS events_list
(
event_id         BIGINT REFERENCES events (event_id)             ON DELETE CASCADE,
compilation_id   BIGINT REFERENCES compilations (compilation_id) ON DELETE CASCADE,
 PRIMARY KEY (event_id, compilation_id)
);
CREATE TABLE IF NOT EXISTS like_list
(
like_id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
event_id     BIGINT NOT NULL REFERENCES events (event_id),
user_id      BIGINT NOT NULL REFERENCES users (user_id),
is_positive BOOLEAN NOT NULL
);