version: '3.8'
services:
  stats-server:
    build: stats-server/server
    image: stats
    container_name: stats-server
    ports:
        - "9090:9090"
    depends_on:
        - stats-db
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
        - SPRING_DATASOURCE_USER=root
        - SPRING_DATASOURCE_PASSWORD=root
  stats-db:
      image: postgres:13.7-alpine
      container_name: stats-db
      volumes:
        - /var/lib/postgresql/data/
      ports:
        - "6541:5432"
      environment:
        - POSTGRES_DB=stats
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
  ewm-service:
    build: ewm-service
    image: ewm-service
    container_name: ewm-service